name: Wake word
skillMetadata:
  sections:
    - name: Processing Settings
      fields:
        - type: label
          label: cairfull this setting take up to 1,5 GB Space on disk and take up to 20 minutes to convert mp3 to wav
        - name: soundbackup
          type: checkbox
          label: Use Public Domain Sounds Backup
          value: "false"
          placeholder: Public Domain Sounds Backup
    - name: Data upload to Precise-Community-Data
      fields:
        - name: savewakewords
          type: checkbox
          label: save wakewords
          value: "false"
          placeholder: demo prompt in the input box
        - name: repo
          type: text
          label: repository for upload
          value: "https://github.com/MycroftAI/Precise-Community-Data.git"
        - name: selling
          type: number
          value: "15"
          label: Sell wake word numbers
    - name: Git Settings vor Upload
      fields:
         - name: localgit
           type: text
           label: Git Username
           value: ""
         - name: gitpass
           type: password
           value: ""
           label: Git Password
