name: Wake word
skillMetadata:
  sections:
    - name: Data upload to Precise-Community-Data
      fields:
        - name: upload
          type: checkbox
          label: upload aktiv
          value: "false"
          placeholder: demo prompt in the input box
        - name: repo
          type: text
          label: repository for upload
          value: "https://github.com/MycroftAI/Precise-Community-Data.git"
